# Versão "com patch" (base + enxuta e recente)
FROM python:3.11-slim

ENV DEBIAN_FRONTEND=noninteractive PIP_NO_CACHE_DIR=1     PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

# Pacotes mínimos (evitar inchar a imagem)
RUN apt-get update && apt-get install -y --no-install-recommends     ca-certificates  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY app.py .
EXPOSE 5000
CMD ["python", "app.py"]
