services:
  firewall_lab3_kali:
    platform: linux/amd64
    container_name: firewall_lab3_kali
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.kali
    command: sleep infinity
    privileged: true
    networks:
      firewall_lab3_network:
        ipv4_address: 10.3.0.11

  firewall_lab3_ubuntu:
    platform: linux/amd64
    container_name: firewall_lab3_ubuntu
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu
    command: sleep infinity
    privileged: true
    networks:
      firewall_lab3_network:
        ipv4_address: 10.3.0.10

  firewall_lab3_gui:
    platform: linux/amd64
    container_name: firewall_lab3_gui
    image: consol/ubuntu-xfce-vnc
    privileged: true
    ports:
      - "5903:5901"
      - "6083:6901"
    environment:
      - VNC_PW=kenseilab
    networks:
      firewall_lab3_network:
        ipv4_address: 10.3.0.12

networks:
  firewall_lab3_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/24
