version: '3.8'
services:
  kali:
    build:
      context: .
      dockerfile: Dockerfile.kali-msf
    image: kensei/kali-msf:latest
    container_name: kensei_kali
    tty: true
    stdin_open: true
    volumes:
      - ./workspace:/home/kali/investigations
    networks:
      - kensei_net
    platform: ${PLATFORM:-linux/amd64}
# Metasploit exposed port is optional when using msfconsole inside Kali
#    ports:
#      - "4444:4444"

networks:
  kensei_net:
    driver: bridge
