version: '3.8'
services:
  kali:
    image: kalilinux/kali-rolling
    container_name: kensei_kali
    tty: true
    stdin_open: true
    volumes:
      - ./workspace:/home/kali/investigations
    networks:
      - kensei_net
    platform: ${PLATFORM:-linux/amd64}

  metasploit:
    image: metasploitframework/metasploit-framework:latest
    container_name: kensei_msf
    tty: true
    stdin_open: true
    ports:
      - "4444:4444"
    volumes:
      - ./msfdata:/msf
    networks:
      - kensei_net
    environment:
      - MSF_DATABASE_CONFIG=/msf/config/database.yml
    platform: ${PLATFORM:-linux/amd64}

networks:
  kensei_net:
    driver: bridge
